packages:
  - src/zod/client
  - src/zod/server
  - src/routing
  - src/redis
  - src/react-lab
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - prisma
  - sqlite3
